name: Build all outputs

on:
  workflow_dispatch:
  push:
    paths:
      - "packages/**"
  repository_dispatch:
    types:
      - trigger-build

jobs:
  nix-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - id: set-matrix
        name: Generate Nix Matrix
        run: |
          ./ci-matrix.sh > "$GITHUB_OUTPUT"

  nix-build:
    needs: nix-matrix
    if: ${{ needs.nix-matrix.outputs.matrix != '' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.nix-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v17
        with:
          extra-conf: |
            substituters = https://cache.nixos.org https://nix-community.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

      - name: Set up Attic cache
        uses: ryanccn/attic-action@v0.3.2
        with:
          endpoint: https://attic.eleonora.gay
          cache: default
          token: ${{ secrets.ATTIC_TOKEN }}

      - run: nix build -L ".#${{ matrix.attr }}"
