name: build-all

on:
  push:
    paths:
      - "packages/**"
      - ".github/workflows/**"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=github:nixos/nixpkgs/e1fa12d4f6c6fe19ccb59cac54b5b3f25e160870

      - name: Enable Cachix
        uses: cachix/cachix-action@v14
        with:
          name: 42loco42
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Run nixci
        run: nix run .#nixci
