name: build-all
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Enable Nix caching
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Install nixci and cachix
        uses: yaxitech/nix-install-pkgs-action@v3
        with:
          packages: "nixpkgs#nixci, cachix"
      - name: Run nixci
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
        run: |
          set -eo pipefail
          nixci | cachix push 42loco42
