name: build-all
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Install nixci
        uses: yaxitech/nix-install-pkgs-action@v3
        with:
          packages: "nixpkgs#nixci"
      - name: Run nixci
        run: nixci
