name: Build all outputs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - "packages/**"

jobs:
  nix-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v12
      - id: set-matrix
        name: Generate Nix Matrix
        run: |
          set -Eeu
          matrix="$(nix run .#matrix)"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  nix-build:
    needs: nix-matrix
    if: ${{ needs.nix-matrix.outputs.matrix != '' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{fromJSON(needs.nix-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v12
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - run: nix run .#build -- "${{ matrix.attr }}"
        env:
          ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}
