name: example
version: 0.1.0

ghc-options: -Wall

dependencies:
  - name: base
    mixin:
      - hiding (Prelude)
  - name: relude
    mixin:
      - (Relude as Prelude)
      - ''
  - flow

executable:
  main: Main.hs
  source-dirs: app
